export const INITIAL_FETCH = "INITIAL_FETCH";
export const FETCH_GLOBAL_STAT_SUCESS = "FETCH_GLOBAL_STAT_SUCESS";
export const FETCH_GLOBAL_STAT_FAILED = "FETCH_GLOBAL_STAT_FAILED";
export const FETCH_GLOBAL_DAILY_SUCESS = "FETCH_GLOBAL_DAILY_SUCESS";
export const FETCH_GLOBAL_DAILY_FAILED = "FETCH_GLOBAL_DAILY_FAILED";
export const IS_LOADING = "IS_LOADING";
export const UNLOADED = "UNLOADED";